### ISSUE TITLE
Saúl Zamora Solórzano

### ISSUE THREAD

**Issue by GenomicENG** [pgalvez9/DevOps2022-1#12]
- [ ] ¿Qué hace un Product Owner?
- [ ] ¿Para qué se utiliza el framework Scrum?
- [ ] ¿Cuál es el papel del Scrum Master?

**Comment by Sebastian-Polo** [comment]
1. Representa las partes interesadas internas y externas, debe maximizar el valor entregado, es la persona responsable de asegurar que el equipo aporte valor al negocio.
2. Es orientado al desarrollo de una labor colaborativa y en equipo para implementaciones ágiles
3. Se encarga de conseguir el equipo que conozca y sienta los principios y valores de Agile, es facilitador de reuniones, siendo el coach y líder al servicio del equipo.
