### ISSUE TITLE
Jesus Alejandro 

### ISSUE THREAD

**Issue by jesusarzgm** [pgalvez9/DevOps2022-1#14]
-[] ¿ Que significa SCRUM?
-[] ¿ Como se divide la jerarquización ?
-[] ¿ Para que sirve SCRUM?

**Comment by JoaquinDguezG** [comment]
- [ ] Tiene como significado una formación fija, cuya función es avanzar como equipo
- [ ] Project Owner, Scrum Master, Software Team, Equipo de desarrollo
- [ ] Sirve para gestionar proyectos, de una manera iterativa y ágil
