### ISSUE TITLE
Pedro Galvez

### ISSUE THREAD

**Issue by pgalvez9** [pgalvez9/DevOps2022-1#2]
- [ ]  Que hace el product owner
- [ ]  Que hace el scrum master
- [ ]  Dime que es el daily meeting

**Comment by LosAngel1** [comment]
El product owner es el encargado de filtrar al stake holder, es como un embajador. También es el más interesado en que el producto salga y quién maximiza el retorno de inversión.

El scrum master es el mediador, el facilitador; es quien se pelea con quien sea necesario para quitar los bloqueos. El mejor scrum master es el que hace que lo despidan.

Es una junta entre el scrum máster y el equipo de desarrollo que dura 15 minutos en donde se discute que se hizo ayer, que se hará hoy y si hay algún bloqueo.
