### ISSUE TITLE
Ángel González

### ISSUE THREAD

**Issue by LosAngel1** [pgalvez9/DevOps2022-1#4]
- [x] ¿Qué es un sprint?

- [x] ¿Cuándo se decide la duración de los sprints?

- [x] ¿Qué es un Product Backlog Item?

**Comment by Migueldj** [comment]
**¿Qué es un sprint?
- Es un tiempo determinado en que se resuelven "n" cantidad de items del Product Backlog 
**¿Cuándo se decide la duración de los sprints?
- Desde el principio y se recomienda que sean de una duración menor a un mes
**¿Qué es un Product Backlog Item?
-Da valor al producto,  parámetro del proyecto a cumplir, tiene su "definition of done" y el conjunto de estos forman el product backlog.
